services:
  node:
    build: .
    # container_name: cpos_node
    deploy:
      replicas: 25
    volumes:
      - .:/cpos
    ports:
      - "8888"
    environment:
      - BEACON_IP=cpos_beacon
      - BEACON_PORT=9000
      - PORT=8888
      - GENESIS_TIMESTAMP=${START_TIME:-0}
    command: /bin/bash demo/run_node.sh
  beacon:
    build: .
    container_name: cpos_beacon
    # network_mode: "host"
    volumes:
      - .:/cpos
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
