services:
  node:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    # container_name: cpos_node
    depends_on:
      - beacon
    deploy:
      replicas: 5
      placement:
            max_replicas_per_node: 1
    # volumes:
    #   - .:/cpos
    ports:
      - "8888"
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=cpos_beacon
      - BEACON_PORT=9000
      - PORT=8888
    command: /bin/bash demo/run_node.sh
  beacon:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    container_name: cpos_beacon
    deploy:
      placement:
          constraints:
            - node.labels.mynode == join
    # network_mode: "host"
    # volumes:
    #   - .:/cpos
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
