services:
  node:
    build: .
    # container_name: cpos_node
    deploy:
      replicas: 10
    volumes:
      - ./demo:/cpos/demo
    ports:
      - "8888"
    environment:
      - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_PORT=9000
      - PORT=8888
      - GENESIS_TIMESTAMP=1686584178
    command: /bin/bash demo/run_node.sh
  beacon:
    build: .
    container_name: cpos_beacon
    network_mode: "host"
    volumes:
      - ./demo:/cpos/demo
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
