services:
  beacon:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    #container_name: cpos_beacon
    deploy:
      placement:
          constraints:
            - node.role == manager
    # network_mode: "host"
    networks:
      # - host
      - test
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "9000:9000"
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
  node:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    # container_name: cpos_node
    depends_on:
      - beacon
    deploy:
      replicas: 20
      # endpoint_mode: dnsrr
      placement:
          max_replicas_per_node: 3
          constraints:
            - node.role == worker
            # - node.labels.mynode == deterlab
    # network_mode: "host"
    networks:
      - test
      # - host
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "8888:8888"
      # - target: 8888
      #   published: 8888
      #   mode: host
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
    command: /bin/bash demo/run_node.sh
  # node2:
  #   image: georgejuniorg/cpos_v2
  #   build: .
  #   tty: true
  #   depends_on:
  #     - beacon
  #   deploy:
  #     replicas: 20
  #     placement:
  #         max_replicas_per_node: 1
  #         # constraints:
  #         #   - node.role == worker
  #   networks:
  #     - host
  #   environment:
  #     - BEACON_IP=join.dca.fee.unicamp.br
  #     - BEACON_PORT=9000
  #     - PORT=8889
  #   command: /bin/bash demo/run_node.sh

networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/8"
# test:
#   name: test
#   driver: overlay
#   attachable: true
  # host:
  #   name: host
  #   external: true
