services:
  beacon:
    image: filipefranco/cpos_v2
    build: .
    tty: true
    deploy:
      placement:
          constraints:
            - node.role == manager
    networks:
      # - host
      - test
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "9000:9000"
    environment:
      - PORT=9000
      - NUM_PEERS_SEND=${NUM_PEER:-5}           # number of peers sent by beacon to nodes who just entered or need more
      - ROUND_TIME=${ROUND_TIME:-10}
    command: /bin/bash demo/run_beacon.sh

  node:
    image: filipefranco/cpos_v2
    build: .
    tty: true
    depends_on:
      - beacon
    deploy:
      replicas: ${NODE_REPLICAS:-25}
      placement:
          max_replicas_per_node: 2
          constraints:
            - node.role == worker
            # - node.labels.mynode == deterlab
    networks:
      - test
      # - host
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "8888:8888"
      # - target: 8888
      #   published: 8888
      #   mode: host
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
      - ROUND_TIME=${ROUND_TIME:-10}
      - TOLERANCE=2
      - TAU=${TAU:-3}
      - TOTAL_STAKE=25
      - MOCK_TRANSACTIONS=true           # set to true to use randomly generated transactions
      - MAXIMUM_NUM_PEERS=${MAXIMUM_NUM_PEERS:-7}              # maximum number of peers a node can have
      - MINIMUM_NUM_PEERS=${MINIMUM_NUM_PEERS:-4}              # minimum number of peers a node can have
      - BROADCAST_CREATED_BLOCK=true     
      - BROADCAST_RECEIVED_BLOCK=true
      
      # Be careful not to commit the following information to github
      - SSH_ADDRESS=
      - SSH_PASSWORD=
      - SCP_PATH=${SCP_PATH}

    command: /bin/bash demo/run_node.sh

  node_dishonest:
    image: filipefranco/cpos_v2
    build: .
    tty: true
    depends_on:
      - beacon
    deploy:
      replicas: ${NODE_DISHONEST_REPLICAS:-0} 
      placement:
          max_replicas_per_node: 1
          constraints:
            - node.role == worker
            # - node.labels.mynode == deterlab
    networks:
      - test
      # - host
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "8888:8888"
      # - target: 8888
      #   published: 8888
      #   mode: host
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
      - ROUND_TIME=${ROUND_TIME:-10}
      - TOLERANCE=2
      - TAU=${TAU:-3}
      - TOTAL_STAKE=25
      - MOCK_TRANSACTIONS=true           # set to true to use randomly generated transactions
      - MAXIMUM_NUM_PEERS=${MAXIMUM_NUM_PEERS:-7}              # maximum number of peers a node can have
      - MINIMUM_NUM_PEERS=${MINIMUM_NUM_PEERS:-4}              # minimum number of peers a node can have
      - BROADCAST_CREATED_BLOCK=${DISHONEST_BROADCAST_CREATED_BLOCK:-false} 
      - BROADCAST_RECEIVED_BLOCK=${DISHONEST_BROADCAST_RECEIVED_BLOCK:-true} 
      
      # Be careful not to commit the following information to github
      - SSH_ADDRESS=
      - SSH_PASSWORD=
      - SCP_PATH=${SCP_PATH}

    command: /bin/bash demo/run_node.sh

networks:
  test:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.60.0.0/16"
# test:
#   name: test
#   driver: overlay
#   attachable: true
  # host:
  #   name: host
  #   external: true
