services:
  beacon:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    deploy:
      placement:
          constraints:
            - node.role == manager
    networks:
      # - host
      - test
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "9000:9000"
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
  node:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    depends_on:
      - beacon
    deploy:
      replicas: 20
      placement:
          max_replicas_per_node: 1
          constraints:
            - node.role == worker
            # - node.labels.mynode == deterlab
    networks:
      - test
      # - host
    # volumes:
    #   - .:/cpos
    # ports:
    #   - "8888:8888"
      # - target: 8888
      #   published: 8888
      #   mode: host
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
    command: /bin/bash demo/run_node.sh

networks:
  test:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.60.0.0/16"
# test:
#   name: test
#   driver: overlay
#   attachable: true
  # host:
  #   name: host
  #   external: true
