services:
  beacon:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    #container_name: cpos_beacon
    deploy:
      placement:
          constraints:
            - node.role == manager
    # network_mode: "host"
    # networks:
    #   - cpos_test
    # volumes:
    #   - .:/cpos
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
    command: /bin/bash demo/run_beacon.sh
  node:
    image: georgejuniorg/cpos_v2
    build: .
    tty: true
    # container_name: cpos_node
    depends_on:
      - beacon
    deploy:
      replicas: 1
      placement:
          max_replicas_per_node: 1
          constraints:
            - node.role == worker
            - node.labels.mynode == deterlab
    # networks:
    #   - cpos_test
    # volumes:
    #   - .:/cpos
    ports:
      - "8888"
    environment:
      # - BEACON_IP=join.dca.fee.unicamp.br
      - BEACON_IP=beacon
      - BEACON_PORT=9000
      - PORT=8888
    command: /bin/bash demo/run_node.sh

# networks:
#   cpos_test:
#     driver: overlay
#     internal: true
