CREATE TABLE IF NOT EXISTS localChains (
        indx integer(100) NOT NULL,
        id varchar(255) NOT NULL,
        round integer,
        prev_hash varchar(255),
        hash varchar(255) NOT NULL,
        owner_pubkey varchar(255),
        merkle_root varchar(255),
        transactions longtext,
        arrive_time integer,
        fork integer,
        stable integer,
        subuser integer,
        proof_hash varchar(255),
        numSuc integer,
        round_stable integer default 0,
        PRIMARY KEY (id,indx))